// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchcERIGO8v0bIBWlHbmG1ZHqO3H97tJs',
    appId: '1:683065706500:web:6271710cb5e0f0a24d4d51',
    messagingSenderId: '683065706500',
    projectId: 'mynotes-yosef-flutter',
    authDomain: 'mynotes-yosef-flutter.firebaseapp.com',
    storageBucket: 'mynotes-yosef-flutter.firebasestorage.app',
    measurementId: 'G-PL2FWJL2X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD826az9SxOuLNzJF7zheo7ElidInB6BO0',
    appId: '1:683065706500:android:b1a450caf92d6d6b4d4d51',
    messagingSenderId: '683065706500',
    projectId: 'mynotes-yosef-flutter',
    storageBucket: 'mynotes-yosef-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhMsnBbNq4WFT1iSWEB8S089M3w-TsZ5I',
    appId: '1:683065706500:ios:652acdf06d9eb0fc4d4d51',
    messagingSenderId: '683065706500',
    projectId: 'mynotes-yosef-flutter',
    storageBucket: 'mynotes-yosef-flutter.firebasestorage.app',
    iosBundleId: 'com.yosef.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhMsnBbNq4WFT1iSWEB8S089M3w-TsZ5I',
    appId: '1:683065706500:ios:652acdf06d9eb0fc4d4d51',
    messagingSenderId: '683065706500',
    projectId: 'mynotes-yosef-flutter',
    storageBucket: 'mynotes-yosef-flutter.firebasestorage.app',
    iosBundleId: 'com.yosef.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchcERIGO8v0bIBWlHbmG1ZHqO3H97tJs',
    appId: '1:683065706500:web:a34cce306fdd7c614d4d51',
    messagingSenderId: '683065706500',
    projectId: 'mynotes-yosef-flutter',
    authDomain: 'mynotes-yosef-flutter.firebaseapp.com',
    storageBucket: 'mynotes-yosef-flutter.firebasestorage.app',
    measurementId: 'G-KP15HZFV7Z',
  );
}
